CREATE TABLE tb_etnia (
    id_etnia integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ds_etnia text NULL,
    CONSTRAINT "PK_tb_etnia" PRIMARY KEY (id_etnia)
);

CREATE TABLE tb_exame (
    id_exame integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nm_exame text NULL,
    CONSTRAINT "PK_tb_exame" PRIMARY KEY (id_exame)
);

CREATE TABLE tb_laudo (
    id_laudo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_medico_laudo integer NOT NULL,
    id_medico_aprovacao integer NOT NULL,
    ds_laudo text NULL,
    ds_recusa text NULL,
    status character(1) NOT NULL,
    CONSTRAINT "PK_tb_laudo" PRIMARY KEY (id_laudo)
);

CREATE TABLE tb_medico (
    id_medico integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nm_medico text NULL,
    crm text NULL,
    email text NULL,
    CONSTRAINT "PK_tb_medico" PRIMARY KEY (id_medico)
);

CREATE TABLE tb_paciente (
    cpf_paciente text NOT NULL,
    nm_paciente text NULL,
    tp_sexo character(1) NOT NULL,
    "IdEtnia" integer NOT NULL,
    dt_nascimento timestamp without time zone NOT NULL,
    CONSTRAINT "PK_tb_paciente" PRIMARY KEY (cpf_paciente),
    CONSTRAINT "FK_tb_paciente_tb_etnia_IdEtnia" FOREIGN KEY ("IdEtnia") REFERENCES tb_etnia (id_etnia) ON DELETE CASCADE
);

CREATE TABLE tb_docente (
    id_docente integer NOT NULL,
    ds_titulacao text NULL,
    CONSTRAINT "PK_tb_docente" PRIMARY KEY (id_docente),
    CONSTRAINT "FK_tb_docente_tb_medico_id_docente" FOREIGN KEY (id_docente) REFERENCES tb_medico (id_medico) ON DELETE CASCADE
);

CREATE TABLE tb_login (
    "Id" integer NOT NULL,
    login text NULL,
    password text NULL,
    CONSTRAINT "PK_tb_login" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tb_login_tb_medico_Id" FOREIGN KEY ("Id") REFERENCES tb_medico (id_medico) ON DELETE CASCADE
);

CREATE TABLE tb_residente (
    id_residente integer NOT NULL,
    dt_residencia timestamp without time zone NOT NULL,
    CONSTRAINT "PK_tb_residente" PRIMARY KEY (id_residente),
    CONSTRAINT "FK_tb_residente_tb_medico_id_residente" FOREIGN KEY (id_residente) REFERENCES tb_medico (id_medico) ON DELETE CASCADE
);

CREATE TABLE tb_pedido_exame (
    "IdPedidoExame" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CpfPaciente" text NULL,
    "IdMedico" integer NOT NULL,
    "IdExame" integer NOT NULL,
    dt_exame timestamp without time zone NOT NULL,
    ds_hipotese_diagnostica text NULL,
    ds_recomendacoes text NULL,
    CONSTRAINT "PK_tb_pedido_exame" PRIMARY KEY ("IdPedidoExame"),
    CONSTRAINT "FK_tb_pedido_exame_tb_paciente_CpfPaciente" FOREIGN KEY ("CpfPaciente") REFERENCES tb_paciente (cpf_paciente) ON DELETE RESTRICT,
    CONSTRAINT "FK_tb_pedido_exame_tb_exame_IdExame" FOREIGN KEY ("IdExame") REFERENCES tb_exame (id_exame) ON DELETE CASCADE,
    CONSTRAINT "FK_tb_pedido_exame_tb_medico_IdMedico" FOREIGN KEY ("IdMedico") REFERENCES tb_medico (id_medico) ON DELETE CASCADE
);

CREATE INDEX "IX_tb_paciente_IdEtnia" ON tb_paciente ("IdEtnia");

CREATE INDEX "IX_tb_pedido_exame_CpfPaciente" ON tb_pedido_exame ("CpfPaciente");

CREATE INDEX "IX_tb_pedido_exame_IdExame" ON tb_pedido_exame ("IdExame");

CREATE INDEX "IX_tb_pedido_exame_IdMedico" ON tb_pedido_exame ("IdMedico");